::Const.RF_VampireBloodHead <- [
	[
		"bust_rf_vampire_blood_head_01_01",
		"bust_rf_vampire_blood_head_01_02",
		"bust_rf_vampire_blood_head_01_03"
	],
	[
		"bust_rf_vampire_blood_head_02_01",
		"bust_rf_vampire_blood_head_02_02",
		"bust_rf_vampire_blood_head_02_03"
	],
	[
		"bust_rf_vampire_blood_head_03_01",
		"bust_rf_vampire_blood_head_03_02",
		"bust_rf_vampire_blood_head_03_03"
	]
];
::Const.RF_VampireLordBloodHead <- [
	[
		"bust_rf_vampire_lord_blood_head_01_01",
		"bust_rf_vampire_lord_blood_head_01_02",
		"bust_rf_vampire_lord_blood_head_01_03"
	],
	[
		"bust_rf_vampire_lord_blood_head_02_01",
		"bust_rf_vampire_lord_blood_head_02_02",
		"bust_rf_vampire_lord_blood_head_02_03"
	],
	[
		"bust_rf_vampire_lord_blood_head_03_01",
		"bust_rf_vampire_lord_blood_head_03_02",
		"bust_rf_vampire_lord_blood_head_03_03"
	]
];
::Const.HairColors.RF_Draugr <- [
	"grey",
	"grey",
	"grey",
	"black"
];
